#!/usr/bin/env python3
"""Anti-drift tests for the committed Codex marketplace plugin mirror.

``plugins/token-optimizer/`` is the nested Codex marketplace plugin directory
regenerated from the canonical repo-root content by
``scripts/sync-codex-marketplace-plugin.sh`` (Codex CLI only resolves
marketplace plugins that live in a subdirectory, not at the repo root). The
mirror can silently drift from the source it was generated off -- a fix applied
to ``hooks/run.py`` or ``hooks/userpromptsubmit_runner.py`` at the root but not
re-mirrored is invisible until the release gate rejects it, or worse, until a
Codex user hits the stale bug.

These tests are the tripwire (analogous to the Cowork
``test_rebuild_emit_committed_leaves_git_clean`` / ``test_cowork_committed_plugin``):

  (a) rebuilding via ``sync-codex-marketplace-plugin.sh`` leaves ``git status``
      clean for ``plugins/token-optimizer/`` (no drift), and
  (b) every ``hooks/*.py`` (and ``python-launcher.sh``) in the mirror is
      byte-identical to the root copy, so a one-sided hook edit fails RED at
      edit time instead of at the release gate. ``hooks.json`` is intentionally
      NOT byte-compared here: the sync script strips the ``async`` keys Codex
      does not support, so the mirror equals the root modulo those keys (the
      rebuild test in (a) guards that parity end-to-end).

Run: python3 -m pytest tests/test_codex_marketplace_plugin.py -q
"""

from __future__ import annotations

import hashlib
import os
import subprocess
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
ROOT_HOOKS = REPO / "hooks"
MIRROR = REPO / "plugins" / "token-optimizer"
MIRROR_HOOKS = MIRROR / "hooks"
SYNC_SCRIPT = REPO / "scripts" / "sync-codex-marketplace-plugin.sh"

# hooks.json is regenerated by the sync script with the async keys stripped
# (Codex compatibility, issue #83), so it is intentionally NOT byte-identical
# to the root hooks.json. The rebuild-leaves-git-clean test guards its parity.
# Everything else under hooks/ (the .py launchers + the bash launcher) MUST be
# byte-identical.
NON_IDENTICAL = {"hooks.json"}


def _git(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", *args], cwd=REPO, capture_output=True, text=True, check=False
    )


def _relative_files(root: Path) -> set[str]:
    found = set()
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in ("__pycache__", ".pytest_cache")]
        for name in filenames:
            if name.endswith(".pyc"):
                continue
            found.add(os.path.relpath(os.path.join(dirpath, name), root))
    return found


def _digest(path: Path) -> str:
    with open(path, "rb") as handle:
        return hashlib.sha256(handle.read()).hexdigest()


# --------------------------------------------------------------------------- #
# (a) rebuild leaves git clean (no drift)
# --------------------------------------------------------------------------- #


@pytest.mark.skipif(
    sys.platform == "win32",
    reason="sync-codex-marketplace-plugin.sh is a bash release-gate step run on "
    "POSIX CI + dev machines; under Windows git-bash it emits UTF-16/exits non-zero. "
    "Windows users consume the pre-built committed mirror, they never regenerate it, "
    "so mirror reproducibility is verified on POSIX, not here.",
)
def test_rebuild_codex_marketplace_leaves_git_clean():
    """Regenerating plugins/token-optimizer/ via the sync script must produce
    no git diff -- the committed mirror is reproducible from the canonical
    root content. Direct analog of test_rebuild_emit_committed_leaves_git_clean
    for the Cowork committed plugin."""
    if _git("rev-parse", "--is-inside-work-tree").returncode != 0:
        pytest.skip("not a git work tree; cannot check for Codex mirror drift")
    if not SYNC_SCRIPT.is_file():
        pytest.skip("sync-codex-marketplace-plugin.sh not present")

    proc = subprocess.run(
        ["bash", str(SYNC_SCRIPT)],
        cwd=REPO,
        capture_output=True,
        text=True,
        check=False,
    )
    assert proc.returncode == 0, (
        f"sync-codex-marketplace-plugin.sh failed (rc={proc.returncode}):\n"
        f"stdout:\n{proc.stdout}\nstderr:\n{proc.stderr}"
    )

    status = _git("status", "--porcelain", "--", "plugins/token-optimizer")
    assert status.returncode == 0, status.stderr
    assert status.stdout.strip() == "", (
        "rebuilding the Codex marketplace mirror produced a diff (drift):\n"
        f"{status.stdout}\n"
        "The committed mirror is not reproducible from "
        "scripts/sync-codex-marketplace-plugin.sh; rerun the script and commit."
    )


# --------------------------------------------------------------------------- #
# (b) hooks/*.py (+ launcher) byte-identical to root
# --------------------------------------------------------------------------- #


def test_codex_mirror_hooks_byte_identical_to_root():
    """Every hooks file EXCEPT hooks.json must be byte-identical between the
    root and the Codex mirror. Catches a one-sided edit to run.py /
    userpromptsubmit_runner.py / module_runner.py / python-launcher.sh that the
    release gate would otherwise catch only at tag time."""
    assert ROOT_HOOKS.is_dir(), "root hooks/ missing"
    assert MIRROR_HOOKS.is_dir(), "plugins/token-optimizer/hooks/ mirror missing"

    root_files = _relative_files(ROOT_HOOKS)
    mirror_files = _relative_files(MIRROR_HOOKS)

    # The mirror must carry every root hooks file (a missing mirror file is a
    # shipping break: Codex hook setup resolves hooks via the plugin root).
    missing_in_mirror = sorted(root_files - mirror_files)
    assert not missing_in_mirror, (
        "These hooks files are missing from the Codex mirror:\n  "
        + "\n  ".join(missing_in_mirror)
        + "\n\nRerun scripts/sync-codex-marketplace-plugin.sh."
    )

    # hooks.json is intentionally different (async stripping); everything else
    # must be byte-identical.
    comparable = sorted(
        (root_files & mirror_files) - NON_IDENTICAL
    )
    assert comparable, "no comparable hooks files found -- paths are probably wrong"

    drifted = [
        rel
        for rel in comparable
        if _digest(ROOT_HOOKS / rel) != _digest(MIRROR_HOOKS / rel)
    ]
    assert not drifted, (
        "These hooks files differ between the root and the Codex mirror:\n  "
        + "\n  ".join(drifted)
        + "\n\nApply the change to the root copy AND rerun "
        "scripts/sync-codex-marketplace-plugin.sh to re-mirror:\n"
        f"  {os.path.relpath(ROOT_HOOKS, REPO)}/<file>"
    )


def test_codex_mirror_hooks_json_is_async_stipped_root():
    """hooks.json in the mirror must equal the root hooks.json under the sync
    script's two Codex compatibility transforms: every ``async`` key recursively
    removed (issue #83) AND SessionEnd hook timeouts clamped to Codex's 3s cap.
    Guards that the mirror's hooks.json did not drift in any OTHER respect."""
    import json

    # Must match CODEX_SESSION_END_TIMEOUT_CAP in
    # scripts/sync-codex-marketplace-plugin.sh.
    CODEX_SESSION_END_TIMEOUT_CAP = 3

    root_hj = ROOT_HOOKS / "hooks.json"
    mirror_hj = MIRROR_HOOKS / "hooks.json"
    assert root_hj.is_file() and mirror_hj.is_file()

    def _strip_async(o):
        if isinstance(o, dict):
            return {k: _strip_async(v) for k, v in o.items() if k != "async"}
        if isinstance(o, list):
            return [_strip_async(v) for v in o]
        return o

    def _clamp_session_end(doc):
        for group in doc.get("hooks", {}).get("SessionEnd", []):
            for hook in group.get("hooks", []):
                t = hook.get("timeout")
                if isinstance(t, (int, float)) and t > CODEX_SESSION_END_TIMEOUT_CAP:
                    hook["timeout"] = CODEX_SESSION_END_TIMEOUT_CAP
        return doc

    expected = _clamp_session_end(
        _strip_async(json.loads(root_hj.read_text(encoding="utf-8")))
    )
    actual = json.loads(mirror_hj.read_text(encoding="utf-8"))
    assert actual == expected, (
        "plugins/token-optimizer/hooks/hooks.json drifted from the root "
        "hooks.json modulo the async keys and the SessionEnd timeout clamp; "
        "rerun scripts/sync-codex-marketplace-plugin.sh."
    )
